---

- name: create directories
  file:
    path: "{{item.value}}"
    state: directory
    mode: 0755
  with_dict: "{{iniPath}}"

- name: write ini files
  template:
    dest: "{{ iniPath[iniDict.key] if iniPath[iniDict.key] is defined else iniPath['default'] }}/{{iniDict.key}}"
    src: templates/generic_ini.j2
  with_dict: "{{some_ini_files}}"
  loop_control:
    loop_var: iniDict
  when: not iniDict.key == 'resource.ini'

- name: write resource.ini from special template
  vars:
    iniDict: 
      key: 'resource.ini'
      value: "{{some_ini_files['resource.ini']}}"
  template:
    dest: "{{ iniPath[iniDict.key] if iniPath[iniDict.key] is defined else iniPath['default'] }}/{{iniDict.key}}"
    src: templates/resource_ini.j2
